language: java
install: mvn clean install -B -V -Dintegration-tests=true
script:
  - cd cloudsim-plus && mvn versioneye:update; cd ..
  - cd cloudsim-plus && mvn clean test -Dintegration-tests=true jacoco:report; cd ..
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8 
after_script:
    - cd cloudsim-plus && mvn jacoco:report; cd ..
    - curl -L https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.0/codacy-coverage-reporter-4.0.0-assembly.jar > codacy.jar
    #Upload the coverage report to codacy.com. It requires the CODACY_PROJECT_TOKEN environment variable
    - java -jar codacy.jar report -l Java -r cloudsim-plus/target/site/jacoco/jacoco.xml
